## Forward propogation

**Step 0**: Read input and output

In [11]:
import numpy as np
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y = ([[1],[1],[0]])

**Step 1**: Initialize weights and biases with random values 

In [92]:
wh = np.random.randn(4,3)
bh = np.random.rand(1,3)
wout = np.random.randn(3,1)
bout = np.random.randn(1)

In [93]:
print(wh)

[[ 0.21697482  0.2464442   1.3407228 ]
 [-0.35097987  0.44048738  0.26880718]
 [ 0.87678745  1.09203612 -2.0680145 ]
 [-1.01925849  0.31854846 -1.81202312]]


In [94]:
print(bh)

[[0.68612633 0.40682232 0.09867956]]


In [95]:
print(wout)

[[ 0.54196006]
 [ 3.14339811]
 [-1.26598791]]


In [96]:
print(bout)

[-1.55748045]


**Step 2**: Calculate hidden layer input

In [97]:
hidden_layer_input = np.dot(X,wh) + bh

In [98]:
print(hidden_layer_input)

[[ 1.77988861  1.74530264 -0.62861214]
 [ 0.76063012  2.0638511  -2.44063526]
 [-0.68411203  1.16585816 -1.44453638]]


**Step 3**: Perform non-linear transformation on hidden linear input

In [99]:
def sigmoid(X):
    return (1 / (1 + np.exp(- X)))

In [100]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print(hiddenlayer_activations)

[[0.85568311 0.85135935 0.3478253 ]
 [0.68149052 0.88733973 0.08012608]
 [0.33534416 0.76239554 0.19084385]]


**Step 4**: Perform linear and non-linear transformation of hidden layer activation at output layer


In [64]:
output_layer_input = np.dot(hiddenlayer_activations, wout )
output = sigmoid(output_layer_input)

In [101]:
print(output)

[[0.93849154]
 [0.93110585]
 [0.79794218]]


## Backward Propogation

**Step 5**: Calculate gradient of Error(E) at output layer

In [66]:
E = y-output

In [102]:
print(E)

[[ 0.06150846]
 [ 0.06889415]
 [-0.79794218]]


**Step 6**: Compute slope at output and hidden layer

In [103]:
def dsigmoid(y):
    return y * (1.0 - y) 

In [104]:
Slope_output_layer= dsigmoid(output)
Slope_hidden_layer = dsigmoid(hiddenlayer_activations)

**Step 7**: Compute delta at output layer

In [116]:
lr = 1
d_output = E * Slope_output_layer * lr

In [117]:
print(d_output)

[[ 0.00355059]
 [ 0.0044194 ]
 [-0.12865258]]


**Step 8**: Calculate Error at hidden layer

In [118]:
Error_at_hidden_layer = np.dot(d_output, np.transpose(wout))

In [119]:
print(Error_at_hidden_layer)

[[ 0.00192428  0.01116091 -0.004495  ]
 [ 0.00239514  0.01389195 -0.00559491]
 [-0.06972456 -0.40440628  0.16287261]]


**Step 9**: Compute delta at hidden layer

In [120]:
d_hiddenlayer = Error_at_hidden_layer * Slope_hidden_layer

In [121]:
print(d_hiddenlayer)

[[ 0.00023763  0.00141237 -0.00101966]
 [ 0.00051989  0.00138875 -0.00041238]
 [-0.0155408  -0.07325762  0.02515119]]


**Step 10**: Update weight at both output and hidden layer

In [122]:
wout = wout + np.dot(np.transpose(hiddenlayer_activations), d_output) * lr
wh = wh + np.dot(np.transpose(X),d_hiddenlayer) * lr

In [123]:
print(wout)

[[ 0.50486713]
 [ 3.05225829]
 [-1.28895137]]


In [124]:
print(wh)

[[ 0.21773234  0.24924533  1.33929076]
 [-0.36652067  0.36722975  0.29395837]
 [ 0.87754497  1.09483724 -2.06944654]
 [-1.0342794   0.24667959 -1.7872843 ]]


**Step 11**: Update biases at both output and hidden layer

In [113]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * lr
bout = bout + np.sum(d_output, axis=0) * lr

In [114]:
print(bh)

[[0.6859785  0.40611775 0.09891675]]


In [115]:
print(bout)

[-1.55868728]
